spring:
  application:
    name: cards-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cards}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090

accounts:
  service:
    url: ${ACCOUNTS_SERVICE_URL:http://localhost:8080}

loans:
  service:
    url: ${LOANS_SERVICE_URL:http://localhost:8070}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


info:
  app:
    name: "accounts"
    description: "Cards Application"
    version: "1.0.0"


logging:
  level:
    com:
      microservices_template.cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
