apiVersion: v1
name: api-gateway
description: A Helm chart for the api gateway
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../../common"
