services:
  postgres:
    image: postgres:latest
    container_name: microservices-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - microservices

  accounts-service:
    image: ivica890/accounts:v1
    container_name: accounts-service
    environment:
      - DB_URL=jdbc:postgresql://microservices-postgres:5432/accounts
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - LOANS_SERVICE_URL=http://loans-service:8070
      - CARDS_SERVICE_URL=http://cards-service:8090
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - microservices

  cards-service:
    image: ivica890/cards:v1
    container_name: cards-service
    environment:
      - DB_URL=jdbc:postgresql://microservices-postgres:5432/cards
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - ACCOUNTS_SERVICE_URL=http://accounts-service:8080
      - LOANS_SERVICE_URL=http://loans-service:8070
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - microservices

  loans-service:
    image: ivica890/loans:v1
    container_name: loans-service
    environment:
      - DB_URL=jdbc:postgresql://microservices-postgres:5432/loans
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - ACCOUNTS_SERVICE_URL=http://accounts-service:8080
      - CARDS_SERVICE_URL=http://cards-service:8090
    ports:
      - "8070:8070"
    depends_on:
      - postgres
    networks:
      - microservices

  api-gateway:
    image: ivica890/api-gateway2:v1
    container_name: api-gateway
    environment:
      - LOANS_SERVICE_URL=http://loans-service:8070
      - ACCOUNTS_SERVICE_URL=http://accounts-service:8080
      - CARDS_SERVICE_URL=http://cards-service:8090
      - JWK_SET_URI=http://keycloak-auth-server:8080/realms/master/protocol/openid-connect/certs

    ports:
      - "8072:8072"
    depends_on:
      - accounts-service
      - loans-service
      - cards-service
#      - keycloak-auth-server
    networks:
      - microservices

  keycloak-auth-server:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: keycloak-auth-server
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "7080:8080"
    command: start-dev
    networks:
      - microservices

volumes:
  postgres_data:

networks:
  microservices:
