{{- define "common.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  db-username: {{ .Values.global.dbUsername | b64enc }}
  db-password: {{ .Values.global.dbPassword | b64enc }}
{{- end -}}
