{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.common.service.type }}
  ports:
    - port: {{ .Values.common.service.port }}
      targetPort: {{ .Values.common.service.targetPort }}
  selector:
    app: {{ .Release.Name }}
{{- end -}}
