  discovery.docker "flog_scrape" {
    host             = "unix:///var/run/docker.sock"
    refresh_interval = "5s"
  }
    
    discovery.relabel "flog_scrape" {
    targets = []
    
    rule {
    source_labels = ["__meta_docker_container_name"]
    regex         = "/(.*)"
    target_label  = "container"
    }
    
    rule {
    source_labels = ["__meta_docker_container_id"]
    target_label  = "container_id"
    }
    
    rule {
    source_labels = ["__meta_docker_image"]
    regex         = ".*:(.*)"
    target_label  = "image_version"
    }
    
    rule {
    source_labels = ["__meta_docker_network_mode"]
    target_label  = "network_mode"
    }
    
    rule {
    source_labels = ["__meta_docker_label_com_docker_compose_service"]
    target_label  = "service"
    }
  }
    
    loki.source.docker "flog_scrape" {
    host             = "unix:///var/run/docker.sock"
    targets          = discovery.docker.flog_scrape.targets
    forward_to       = [loki.write.default.receiver]
    relabel_rules    = discovery.relabel.flog_scrape.rules
    refresh_interval = "5s"
  }
    
    loki.write "default" {
    endpoint {
    url       = "http://gateway:3100/loki/api/v1/push"
    tenant_id = "tenant1"
    }
    external_labels = {}
  }
