apiVersion: v1
name: loans-service
description: A Helm chart for the loans service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../../common"
