nameOverride: postgres
fullnameOverride: postgres
auth:
  username: postgres
  password: postgres
global:
  postgresql:
    auth:
      postgresPassword: postgres
primary:
  service:
    type: ClusterIP
    port: 5432
  initdb:
    scripts:
      init.sql: |
        CREATE DATABASE accounts;
        CREATE DATABASE cards;
        CREATE DATABASE loans;
